expense_manager/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    # List Accounts of Current Logged-in User
    url(r'^$', views.index, name='index'),
    
    # Create New Account
    url(r'^create/$', views.create, name='create'),
    
    # Show Account Detail
    url(r'^(?P<account_id>[0-9]+)/$', views.detail, name='detail'),
    
    # Edit Existing Account
    url(r'^(?P<account_id>[0-9]+)/edit/$', views.edit, name='edit'),
    
    # List Transactions
    url(r'^(?P<account_id>[0-9]+)/transaction/$', views.list_transaction, name='list_transaction'),
    
    # Add Transaction
    url(r'^(?P<account_id>[0-9]+)/transaction/add/$', views.add_transaction, name='add_transaction'),
    
    # Edit Transaction
    url(r'^(?P<account_id>[0-9]+)/transaction/(?P<transaction_id>[0-9]+)/edit/$', views.edit_transaction, name='edit_transaction'),
    
]

expense_manager/expense_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from expense_manager import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^login/$', views.app_login, name='login'),
    url(r'^logout/$', views.app_logout, name='logout'),
    url(r'^$', views.home, name='home')
]

expense_manager/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    starting_amount = models.DecimalField(max_digits=10,decimal_places=2)
    currency = models.CharField(max_length=3)
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    
class Transaction(models.Model):
    TRANSACTION_TYPE = (
        ('I','Income'),   
        ('E','Expense'),   
    )
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=TRANSACTION_TYPE)
    amount = models.DecimalField(max_digits=10,decimal_places=2)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

expense_manager/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse 
from .models import Account, Transaction
from .repositories.account_repo import AccountRepo 

@login_required
def index(request):
    accounts = Account.objects.filter(user_id= request.user.id)
    context = {'accounts' : accounts}
    return render(request, 'accounts/accounts/list.html', context)

@login_required
def create(request):
    context = {
        'form_mode' : 'add',
        'post_url' : reverse('accounts:create')
    }
    #if request.POST :
        
    return render(request, 'accounts/accounts/form.html', context)
    
@login_required
def edit(request, account_id):
    account = Account.objects.get(id=account_id)
    context = {
        'account' : account,
        'form_mode' : 'edit',
        'post_url' : reverse('accounts:edit', args=[account_id])
    }
    return render(request, 'accounts/accounts/form.html', context)
    
@login_required
def detail(request, account_id):
    account = AccountRepo().get( id=account_id, user_id=request.user.id )
    context = {
        'account' : account,
        'starting_amount_format' : account.currency + ' ' + str(account.starting_amount),
        'balance_format' : account.currency + ' ' + str(account.balance),
    }
    return render(request, 'accounts/accounts/detail.html', context)
    
@login_required
def list_transaction(request, account_id):
    account = AccountRepo().get( id=account_id, user_id=request.user.id )
    transactions = Transaction.objects.filter(account_id=account.id)
    context = {
        'account' : account,
        'transactions' : account.transactions
    }
    return render(request, 'accounts/transactions/list.html', context)
    
@login_required
def add_transaction(request, account_id):
    account = AccountRepo().get( id=account_id, user_id=request.user.id )
    context = {
        'account' : account, 
        'form_mode' : 'add'
    }
    return render(request, 'accounts/transactions/form.html', context)

@login_required
def edit_transaction(request, account_id, transaction_id):
    account = AccountRepo().get( id=account_id, user_id=request.user.id )
    transaction = Transaction.objects.get(id=transaction_id)
    context = {
        'account' : account, 
        'transaction' : transaction, 
        'form_mode' : 'edit'
    }
    return render(request, 'accounts/transactions/form.html', context)

expense_manager/expense_manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.http import require_http_methods

def home(request):
    return render(request, 'frontend/home/home.html')

@require_http_methods(["POST"])
def app_login(request):
    if request.method != 'POST' :
        return redirect('home')
    
    user = authenticate(username=request.POST['username'], password=request.POST['password'])
    if user is not None and user.is_active:
        login(request, user)
    #else:
        #messages.add_message(request, messages.ERROR, "The username and password were incorrect.")
    
    return redirect('home')
    
def app_logout(request):
    logout(request)
    return redirect('home')

expense_manager/accounts/templates/accounts/accounts/detail.html
{% extends "accounts/layout.html" %}

{% block title %}
    Account Details : {{ account.name }}
{% endblock %}


{% block content %}
    <h3>Account Details : {{ account.name }}</h3>
    
    <dl>
        <dt>Starting Amount :</dt>
            <dd>{{ starting_amount_format }}</dd>
        
        <dt>Total Balance :</dt>
            <dd>{{ balance_format }}</dd>
    </dl>
    
{% endblock %}

expense_manager/accounts/templates/accounts/accounts/form.html
{% extends "frontend/layout.html" %}

{% block title %}
    {{ form_mode | title }} Account
{% endblock %}

{% block content %}
    
    <h1>{{ form_mode | title }} Account</h1>
    
    <form method="POST" action="{{ post_url }}">
        
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Account Name</label>
            <input type="text" id="name" name="name" />
        </div>
        
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" id="description" name="description" />
        </div>
        
        <div class="form-group">
            <label for="starting_amount">Starting Amount</label>
            <input type="text" id="starting_amount" name="starting_amount" />
        </div>
        
        <div class="form-group">
            <label for="currency">Currency</label>
            <input type="text" id="currency" name="currency" />
        </div>
        
        <div class="form-group">
            <input type="submit" value="Save"/>
        </div>
        
    </form>
    
{% endblock %}

expense_manager/accounts/templates/accounts/accounts/list.html
{% extends "frontend/layout.html" %}

{% block title %}
    Accounts List
{% endblock %}

{% block content %}
    <h3>Accounts List</h3>
    
    <div class="btn-group">
        <a href="{% url 'accounts:create' %}">Create New Account</a>
    </div>
    
    {% if accounts %}
        <ul>
        {% for account in accounts %}
            <li><a href="{% url 'accounts:detail' account.id %}">{{ account.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No records are available.</p>
    {% endif %}
    
{% endblock %}

expense_manager/accounts/templates/accounts/layout.html
{% extends "frontend/layout.html" %}

{% block module_header %}
<h2><strong>Account</strong> : {{ account.name }}</h2>

<nav>
    <ul>
        <li><a href="{% url 'accounts:detail' account.id %}">Account Details</a></li>
        <li><a href="{% url 'accounts:edit' account.id %}">Edit Account</a></li>
        <li>
            <strong>Transactions</strong>
            <ul>
                <li><a href="{% url 'accounts:list_transaction' account.id %}">List Transactions</a></li>
                <li><a href="{% url 'accounts:add_transaction' account.id %}">Add Transactions</a></li>
            </ul>
        </li>
    </ul>
</nav>
{% endblock %}

{% block content %}{% endblock %}

expense_manager/accounts/templates/accounts/transactions/form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h1>Account Transaction Form</h1>
{% endblock %}

expense_manager/accounts/templates/accounts/transactions/list.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h3>Transaction List</h3>
    
    {% if account.transactions.count > 0 %}
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in account.transactions %}
            <tr>
                <td>{{ transaction.created_on | date:"Y-m-d" }}</td>
                <td>{{ transaction.type_format }}</td>
                <td>{{ account.currency }} {{ transaction.amount }}</td>
                <td>{{ transaction.description }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    
    
    {% endif %}
{% endblock %}

expense_manager/templates/frontend/home/home.html
{% extends "frontend/layout.html" %}

{% block content %}
    <h3>Home Page</h3>
    
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}</p>
    {% else %}
    <p>Please Login to App.</p>
        
    <form action="{% url "login" %}" method="post">
        
        {% csrf_token %}
        
        <input type="text" name="username" value="" placeholder="Username">
        <input type="password" name="password" value="" placeholder="Password">
        <input type="hidden" name="next" value="{{ next }}">
        <input class="btn btn-default" type="submit" value="Login">
        
    </form>
    {% endif %}
    
{% endblock %}

expense_manager/templates/frontend/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Home{% endblock %} - Expense Manager</title>
    <meta charset="utf-8" />
    {% load staticfiles %}
</head>

<body>
    
    <header>
        <h1>Expense Manager <small> - A sample app</small></h1>
    </header>
    
    <div id="navbar">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:index' %}">Accounts</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>

    {% block module_header %}{% endblock %}

    <div id="content">
        
        {% if messages %}
        <ul class="alert messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        {% block content %} Blank {% endblock %}

    </div>
    
    <footer>
        Sample App Created by Ahmedul Haque Abid
    </footer>
    
</body>
</html>